Repository UpendoVentures/Upendo-Dnn-UserManager, pull requests merged in 2023-08, with the labels that each got.

#39 Exception when logged out
  Modules/UserManager/App_LocalResources/AddEdit.resx
  Modules/UserManager/App_LocalResources/AddEditRoles.resx
  Modules/UserManager/App_LocalResources/Index.resx
  Modules/UserManager/App_LocalResources/Shared.resx
  Modules/UserManager/App_LocalResources/UserManageController.resx
  Modules/UserManager/App_LocalResources/UserRoles.resx
  Modules/UserManager/Controllers/RolesManageController.cs
  Modules/UserManager/Controllers/UserManageController.cs
  Modules/UserManager/Upendo.Modules.UserManager.csproj
  Modules/UserManager/Views/RolesManage/Create.cshtml
  Modules/UserManager/Views/RolesManage/Details.cshtml
  Modules/UserManager/Views/RolesManage/Edit.cshtml
  Modules/UserManager/Views/RolesManage/Index.cshtml
  Modules/UserManager/Views/Shared/Error.cshtml
  Modules/UserManager/Views/UserManage/ChangePassword.cshtml
  Modules/UserManager/Views/UserManage/Create.cshtml
  Modules/UserManager/Views/UserManage/Details.cshtml
  Modules/UserManager/Views/UserManage/Edit.cshtml
  Modules/UserManager/Views/UserManage/Index.cshtml
  Modules/UserManager/Views/UserManage/UserRoles.cshtml
Labels: bug

#50 Tasks/1.0 release prep
  Modules/UserManager/App_LocalResources/AddEditRoles.resx
  Modules/UserManager/App_LocalResources/Index.resx
  Modules/UserManager/App_LocalResources/Settings.resx
  Modules/UserManager/App_LocalResources/Shared.resx
  Modules/UserManager/App_LocalResources/UserRoles.resx
  Modules/UserManager/Components/FeatureController.cs
  Modules/UserManager/Controllers/ExampleController.cs
  Modules/UserManager/Controllers/RolesManageController.cs
  Modules/UserManager/Controllers/SettingsController.cs
  Modules/UserManager/Controllers/UserManageController.cs
  Modules/UserManager/Data/ExampleInfoRepository.cs
  Modules/UserManager/Models/DnnModel/AspnetApplications.cs
  Modules/UserManager/Models/DnnModel/AspnetMembership.cs
  Modules/UserManager/Models/DnnModel/AspnetUsers.cs
  Modules/UserManager/Models/DnnModel/Portals.cs
  Modules/UserManager/Models/DnnModel/RoleGroups.cs
  Modules/UserManager/Models/DnnModel/Roles.cs
  Modules/UserManager/Models/DnnModel/UserRoles.cs
  Modules/UserManager/Models/DnnModel/Users.cs
  Modules/UserManager/Models/ExampleInfo.cs
  Modules/UserManager/Models/Interfaces/IExampleInfo.cs
  Modules/UserManager/Models/Settings.cs
  Modules/UserManager/Module.build
  Modules/UserManager/Module.css
  Modules/UserManager/Providers/DataProviders/SqlDataProvider/01.00.00.SqlDataProvider
  Modules/UserManager/Providers/DataProviders/SqlDataProvider/Uninstall.SqlDataProvider
  Modules/UserManager/Upendo.Modules.UserManager.csproj
  Modules/UserManager/Upendo.UserManager.dnn
  Modules/UserManager/Upendo.UserManager_Symbols.dnn
  Modules/UserManager/Utility/Functions.cs
  Modules/UserManager/Utility/RolesRepository.cs
  Modules/UserManager/Utility/UserRepository.cs
  Modules/UserManager/ViewModels/Pagination.cs
  Modules/UserManager/ViewModels/ResultJsonViewModel.cs
  Modules/UserManager/ViewModels/RolesViewModel.cs
  Modules/UserManager/ViewModels/UserViewModel.cs
  Modules/UserManager/Views/Example/Edit.cshtml
  Modules/UserManager/Views/Example/Index.cshtml
  Modules/UserManager/Views/RolesManage/Create.cshtml
  Modules/UserManager/Views/RolesManage/Edit.cshtml
  Modules/UserManager/Views/RolesManage/Index.cshtml
  Modules/UserManager/Views/Settings/Settings.cshtml
  Modules/UserManager/Views/UserManage/Edit.cshtml
  Modules/UserManager/Views/UserManage/Index.cshtml
  Modules/UserManager/Views/UserManage/UserRoles.cshtml
Labels: bug, enhancement, task

#47 Update Create.cshtml
  Modules/UserManager/Upendo.Modules.UserManager.csproj
  Modules/UserManager/Views/UserManage/Create.cshtml
Labels: bug

#51 Resolved usability issues
  Modules/UserManager/App_LocalResources/AddEdit.resx
  Modules/UserManager/Views/UserManage/Create.cshtml
  Modules/UserManager/Views/UserManage/Edit.cshtml
Labels: bug

#53 Updated to be more descriptive for non-developers
  README.md
Labels: enhancement

#54 Update README.md
  README.md
Labels: enhancement

#55 Fixed a silly typo
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/help-and-other-questions.md
Labels: enhancement

#57 user-workflow-usability
  Modules/UserManager/App_LocalResources/AddEditRoles.resx
  Modules/UserManager/App_LocalResources/FeatureController.resx
  Modules/UserManager/App_LocalResources/RolesManageController.resx
  Modules/UserManager/Components/FeatureController.cs
  Modules/UserManager/Controllers/RolesManageController.cs
  Modules/UserManager/Controllers/UserManageController.cs
  Modules/UserManager/Models/DnnModel/Users.cs
  Modules/UserManager/Upendo.Modules.UserManager.csproj
  Modules/UserManager/Utility/Functions.cs
  Modules/UserManager/Utility/RolesRepository.cs
  Modules/UserManager/Utility/UserRepository.cs
  Modules/UserManager/Views/RolesManage/Create.cshtml
  Modules/UserManager/Views/RolesManage/Edit.cshtml
  Modules/UserManager/Views/UserManage/Create.cshtml
  Modules/UserManager/Views/UserManage/Edit.cshtml
  Modules/UserManager/Views/UserManage/Index.cshtml
Labels: enhancement

#58 Security update
  Modules/UserManager/Controllers/UserManageController.cs
  Modules/UserManager/Utility/UserRepository.cs
Labels: enhancement

#60 Added an icon to the readme
  README.md
Labels: task

#64 Unable create new role
  Modules/UserManager/App_LocalResources/RolesManageController.resx
  Modules/UserManager/Controllers/RolesManageController.cs
  Modules/UserManager/Utility/RolesRepository.cs
  Modules/UserManager/Views/RolesManage/Create.cshtml
  Modules/UserManager/Views/RolesManage/Edit.cshtml
Labels: bug

#65 Preparation for release
  Modules/UserManager/Properties/AssemblyInfo.cs
  Modules/UserManager/Upendo.Modules.UserManager.csproj
  Modules/UserManager/Upendo.UserManager.dnn
  Modules/UserManager/Upendo.UserManager_Symbols.dnn
  Modules/UserManager/releasenotes.txt
Labels: task

#66 Sync dev and main
  Modules/UserManager/App_LocalResources/RolesManageController.resx
  Modules/UserManager/Controllers/RolesManageController.cs
  Modules/UserManager/Properties/AssemblyInfo.cs
  Modules/UserManager/Upendo.Modules.UserManager.csproj
  Modules/UserManager/Upendo.UserManager.dnn
  Modules/UserManager/Upendo.UserManager_Symbols.dnn
  Modules/UserManager/Utility/RolesRepository.cs
  Modules/UserManager/Views/RolesManage/Create.cshtml
  Modules/UserManager/Views/RolesManage/Edit.cshtml
  Modules/UserManager/releasenotes.txt
Labels: task

#70 Tasks/release prep
  Build/HccViewsetPackage.targets
  Build/Helpers.targets
  Build/LibraryPackage.targets
  Build/ModulePackage.targets
  Build/SkinPackage.targets
  Modules/UserManager/Module.build
  Modules/UserManager/Properties/AssemblyInfo.cs
  Modules/UserManager/Upendo.UserManager.dnn
  Modules/UserManager/Upendo.UserManager_Symbols.dnn
  Modules/UserManager/releasenotes.txt
  UpendoDnnUserManager.DNN.sln
Labels: task

#77 Issues/issue 75
  Modules/UserManager/Properties/AssemblyInfo.cs
  Modules/UserManager/Providers/DataProviders/SqlDataProvider/01.01.01.SqlDataProvider
  Modules/UserManager/Upendo.Modules.UserManager.csproj
  Modules/UserManager/Upendo.UserManager.dnn
  Modules/UserManager/Upendo.UserManager_Symbols.dnn
  Modules/UserManager/Views/UserManage/Create.cshtml
  Modules/UserManager/releasenotes.txt
Labels: bug, enhancement

#78 Sync dev and main
  Modules/UserManager/Properties/AssemblyInfo.cs
  Modules/UserManager/Providers/DataProviders/SqlDataProvider/01.01.01.SqlDataProvider
  Modules/UserManager/Providers/DataProviders/SqlDataProvider/Uninstall.SqlDataProvider
  Modules/UserManager/Upendo.Modules.UserManager.csproj
  Modules/UserManager/Upendo.UserManager.dnn
  Modules/UserManager/Upendo.UserManager_Symbols.dnn
  Modules/UserManager/Utility/Functions.cs
  Modules/UserManager/Utility/UserRepository.cs
  Modules/UserManager/Views/UserManage/Create.cshtml
  Modules/UserManager/Views/UserManage/Index.cshtml
  Modules/UserManager/releasenotes.txt
Labels: task
