Repository UpendoVentures/Upendo-Dnn-UserManager, pull requests merged in 2024-12, with the labels that each got.

#103 User Manager: Able to Create New Superuser
  Modules/UserManager/Controllers/UserManageController.cs
  Modules/UserManager/Module.css
  Modules/UserManager/Views/UserManage/Create.cshtml
Labels: bug

#104 Tasks/release 1.4.1
  Modules/UserManager/Properties/AssemblyInfo.cs
  Modules/UserManager/Upendo.UserManager.dnn
  Modules/UserManager/Upendo.UserManager_Symbols.dnn
  Modules/UserManager/releasenotes.txt
Labels: task

#105 Syncing branches for 1.4.1 release
  Modules/UserManager/Controllers/UserManageController.cs
  Modules/UserManager/Module.css
  Modules/UserManager/Properties/AssemblyInfo.cs
  Modules/UserManager/Upendo.UserManager.dnn
  Modules/UserManager/Upendo.UserManager_Symbols.dnn
  Modules/UserManager/Views/UserManage/Create.cshtml
  Modules/UserManager/releasenotes.txt
Labels: task

#108 Ability for Superusers to Impersonate Other User Accounts
  Modules/UserManager/App_LocalResources/Impersonate.resx
  Modules/UserManager/App_LocalResources/Shared.resx
  Modules/UserManager/Controllers/UserManageController.cs
  Modules/UserManager/Module.css
  Modules/UserManager/Upendo.Modules.UserManager.csproj
  Modules/UserManager/Views/UserManage/Index.cshtml
Labels: enhancement

#107 Search Should not be Case-Sensitive
  Modules/UserManager/Providers/DataProviders/SqlDataProvider/01.04.01.SqlDataProvider
  Modules/UserManager/Upendo.Modules.UserManager.csproj
  Modules/UserManager/Upendo.UserManager.dnn
  Modules/UserManager/Utility/Functions.cs
Labels: bug

#110 Tasks/release 1.5.0
  Modules/UserManager/App_LocalResources/Impersonate.resx
  Modules/UserManager/App_LocalResources/Index.resx
  Modules/UserManager/Module.css
  Modules/UserManager/Properties/AssemblyInfo.cs
  Modules/UserManager/Providers/DataProviders/SqlDataProvider/01.05.00.SqlDataProvider
  Modules/UserManager/Upendo.Modules.UserManager.csproj
  Modules/UserManager/Upendo.UserManager.dnn
  Modules/UserManager/Upendo.UserManager_Symbols.dnn
  Modules/UserManager/Views/UserManage/Index.cshtml
  Modules/UserManager/releasenotes.txt
  Modules/UserManager/web.config
Labels: task

#111 Syncing branches
  Modules/UserManager/App_LocalResources/Impersonate.resx
  Modules/UserManager/App_LocalResources/Index.resx
  Modules/UserManager/App_LocalResources/Shared.resx
  Modules/UserManager/Controllers/UserManageController.cs
  Modules/UserManager/Module.css
  Modules/UserManager/Properties/AssemblyInfo.cs
  Modules/UserManager/Providers/DataProviders/SqlDataProvider/01.05.00.SqlDataProvider
  Modules/UserManager/Upendo.Modules.UserManager.csproj
  Modules/UserManager/Upendo.UserManager.dnn
  Modules/UserManager/Upendo.UserManager_Symbols.dnn
  Modules/UserManager/Utility/Functions.cs
  Modules/UserManager/Utility/UserRepository.cs
  Modules/UserManager/Views/UserManage/Index.cshtml
  Modules/UserManager/releasenotes.txt
  Modules/UserManager/web.config
Labels: task

#113 Update Index.cshtml
  Modules/UserManager/Views/UserManage/Index.cshtml
Labels: bug

#114 Tasks/release 1.5.1
  Modules/UserManager/Properties/AssemblyInfo.cs
  Modules/UserManager/Upendo.UserManager.dnn
  Modules/UserManager/Upendo.UserManager_Symbols.dnn
  Modules/UserManager/releasenotes.txt
Labels: task

#115 Syncing the branches
  Modules/UserManager/Properties/AssemblyInfo.cs
  Modules/UserManager/Upendo.UserManager.dnn
  Modules/UserManager/Upendo.UserManager_Symbols.dnn
  Modules/UserManager/Views/UserManage/Index.cshtml
  Modules/UserManager/releasenotes.txt
Labels: task
