Repository UpendoVentures/Upendo-Dnn-UserManager, pull requests merged in 2024-05, with the labels that each got.

#89 Role start end date
  Modules/UserManager/App_LocalResources/UserRoles.resx
  Modules/UserManager/Controllers/UserManageController.cs
  Modules/UserManager/Module.css
  Modules/UserManager/Upendo.Modules.UserManager.csproj
  Modules/UserManager/Utility/Functions.cs
  Modules/UserManager/Utility/UserRepository.cs
  Modules/UserManager/ViewModels/RolesViewModel.cs
  Modules/UserManager/ViewModels/UserRoleDates.cs
  Modules/UserManager/Views/Shared/_Layout.cshtml
  Modules/UserManager/Views/UserManage/UserRoles.cshtml
Labels: enhancement

#90 Role start end date
  Modules/UserManager/Controllers/UserManageController.cs
  Modules/UserManager/Utility/UserRepository.cs
  Modules/UserManager/Views/Shared/_Layout.cshtml
  Modules/UserManager/Views/UserManage/UserRoles.cshtml
Labels: bug, enhancement

#91 Tasks/release 01.02.00
  Modules/UserManager/Properties/AssemblyInfo.cs
  Modules/UserManager/Upendo.UserManager.dnn
  Modules/UserManager/Upendo.UserManager_Symbols.dnn
  Modules/UserManager/releasenotes.txt
Labels: task

#92 Merging dev and main
  Modules/UserManager/App_LocalResources/UserManageController.resx
  Modules/UserManager/App_LocalResources/UserRoles.resx
  Modules/UserManager/Controllers/UserManageController.cs
  Modules/UserManager/Module.css
  Modules/UserManager/Properties/AssemblyInfo.cs
  Modules/UserManager/Upendo.Modules.UserManager.csproj
  Modules/UserManager/Upendo.UserManager.dnn
  Modules/UserManager/Upendo.UserManager_Symbols.dnn
  Modules/UserManager/Utility/Functions.cs
  Modules/UserManager/Utility/UserRepository.cs
  Modules/UserManager/ViewModels/RolesViewModel.cs
  Modules/UserManager/ViewModels/UserRoleDates.cs
  Modules/UserManager/Views/Shared/_Layout.cshtml
  Modules/UserManager/Views/UserManage/Create.cshtml
  Modules/UserManager/Views/UserManage/UserRoles.cshtml
  Modules/UserManager/releasenotes-10102.txt
  Modules/UserManager/releasenotes.txt
Labels: task
